const h5Pages = [
  {
    id: 'h5-001',
    title: '跳一跳',
    description: '经典微信小游戏 H5 版，按住蓄力跳跃到下一个方块',
    thumbnail: '',
    url: 'https://www.wesane.com/game/635/',
    category: '游戏',
    featured: true,
  },
  {
    id: 'h5-002',
    title: '物理弹球',
    description: '经典打砖块游戏，考验你的反应速度和角度计算能力',
    thumbnail: '',
    url: 'https://www.wesane.com/game/633/',
    category: '游戏',
    featured: true,
  },
  {
    id: 'h5-003',
    title: '颜色匹配',
    description: '在规定时间内找出不同颜色的色块，挑战你的色感',
    thumbnail: '',
    url: 'https://www.wesane.com/game/626/',
    category: '休闲',
    featured: false,
  },
  {
    id: 'h5-004',
    title: '在线PS',
    description: '网页版 Photoshop 替代方案，无需安装即可使用',
    thumbnail: '',
    url: 'https://www.photopea.com/',
    category: '工具',
    featured: true,
  },
  {
    id: 'h5-005',
    title: '在线思维导图',
    description: '免费在线思维导图工具，支持多人协作编辑',
    thumbnail: '',
    url: 'https://www.mindline.cn/',
    category: '工具',
    featured: false,
  },
  {
    id: 'h5-006',
    title: '文字云生成器',
    description: '输入文字自动生成漂亮的文字云图片，支持多种形状模板',
    thumbnail: '',
    url: 'https://www.wordclouds.com/',
    category: '设计',
    featured: false,
  },
  {
    id: 'h5-007',
    title: '在线钢琴',
    description: '用键盘弹奏钢琴，支持多种音色和录音功能',
    thumbnail: '',
    url: 'https://www.autopiano.cn/',
    category: '音乐',
    featured: false,
  },
  {
    id: 'h5-008',
    title: '白噪音生成器',
    description: '雨声、海浪、森林等自然白噪音，帮助专注和放松',
    thumbnail: '',
    url: 'https://www.noisli.com/',
    category: '生活',
    featured: true,
  },
  {
    id: 'h5-009',
    title: '电子木鱼',
    description: '在线敲木鱼积功德，解压放松小工具',
    thumbnail: '',
    url: 'https://www.wesane.com/game/654/',
    category: '休闲',
    featured: false,
  },
]

export default h5Pages